### ISSUE TITLE
Unexpected operation: filters

### ISSUE THREAD

**Issue by sarcasterXO** [NezuChan/erela.js-filter#4]
**I am using the latest version of this module i.e. `v0.2.3` and getting the error: `Unexpected operation: filters`. I am trying to add the filter when the player is created by using the `playerCreate` event.**

Tried Filters: `Nightcore` & `Vaporwave`
Lavalink Version: `3.3.2.5`.

**Comment by KagChi** [comment]
you need lavalink dev to use filter
